title: Psi-ntific
author: Abhay Hegde
subtitle: Murmurs

url: "https://psintific.github.io"
#baseurl: "/parchment-jekyll"

footer_url: "https://psintific.github.io/about"
footer_text: "Abhay Hegde"

profile-picture: assets/profile.jpg
favicon_location: assets/psintific.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

logo: /assets/logo.png

navbar:
 - name: "About"
   link: "about"
 - name: "Contact"
   link: "contact"
 - name: "Links"
   link: "links"

theme: jekyll-theme-minimal
